;ASCII CODE TO ALPHABET/NUMBER/CHARACTER CONVERSION AS STRING

.MODEL SMALL
.STACK 100H
.CODE

MAIN PROC               
         
    MOV AH,2
    MOV DL,03H
    INT 21H
    
    MOV AH,4CH
    INT 21H
    MAIN ENDP
END MAIN